<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions\" />
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Models\" />
    <Folder Include="Features\Categories\CreateCategory\" />
    <Folder Include="Features\Categories\GetCategoryList\" />
    <Folder Include="Features\Categories\UpdateCategory\" />
    <Folder Include="Features\Comments\AddComment\" />
    <Folder Include="Features\Dashboard\GetDashboardSummary\" />
    <Folder Include="Features\Tickets\AssignTicket\" />
    <Folder Include="Features\Tickets\ChangeStatus\" />
    <Folder Include="Features\Tickets\CloseTicket\" />
    <Folder Include="Features\Tickets\CreateTicket\" />
    <Folder Include="Features\Tickets\GetTicketById\" />
    <Folder Include="Features\Tickets\GetTicketList\" />
    <Folder Include="Features\Tickets\UpdateTicket\" />
  </ItemGroup>

</Project>
